### ISSUE TITLE
Access denied with correct access token

### ISSUE THREAD

**Issue by frederike-ramin** [dblock/slack-sup#100]
Hi there,
first of all: thanks for the tool, it's helping my team greatly. 👍 
I just have a problem accessing my team's data via the API. Not sure if this is an error with the API or the way I'm using it, though. 
I turned on API access (`set api on`) and generated a new access token (`rotate api token`). The bot gave me the following output:

> Team data access via the API is on with a new access token <TOKEN>.
> https://sup.playplay.io/api/teams/<ID>

With exactly these values I executed the following command (as described in [API.md](https://github.com/dblock/slack-sup/blob/master/API.md)):
`curl -H "X-Access-Token:<TOKEN>" "https://sup.playplay.io/api/teams/<ID>" | json_pp`
and got a 401 Access Denied error.

Am I using it wrong? Is maybe the old token displayed in the bot's message that is no longer valid? 
Help would be much appreciated. :)

**Comment by dblock** [comment]
What's your team name/ID? Feel free to email me to dblock at dblock dot org if you don't want that to be public.

**Comment by dblock** [comment]
This was a real bug. Fixed in https://github.com/dblock/slack-sup/commit/aa14c0af1467b80e1d43ff306b8856f555d74269.
