### ISSUE TITLE
Four s'up sessions scheduled at the same time for single user

### ISSUE THREAD

**Issue by roman-kaspar** [dblock/slack-sup#131]
Today I received four s'up invitations.

App settings:

> Team S'Up connects groups of max 3 people on Monday after 9:00 AM every week in (GMT+01:00) Europe/Prague, taking special care to not pair the same people more frequently than every 12 weeks.
Users are opted in by default.
Custom profile team field is not set.

Interestingly, each of the four invitations today had four participants (see above that we have "groups of max 3 people" configured for a S'Up session). There hasn't been any recent changes in the settings of the app (AFAIK), nor to Slack team / workspaces.

I didn't receive any S'Up session invitation last week (not sure if this is relevant).

 So I think there might be a bug in the scheduling code...

**Comment by dblock** [comment]
Confirming that this was a bug, fixed in https://github.com/dblock/slack-sup/commit/7836cec53cdf48fe8ff19320ca68bc750dd56422.
