### ISSUE TITLE
Make the onboarding experience more engaging

### ISSUE THREAD

**Issue by dblock** [dblock/slack-sup#26]
When you install S'Up it DMs slack admins with 

> Hi there! I'm your team's S'Up bot. Thanks for trying me out. Type `help` for instructions. I plan to setup some S'Ups via Slack DM next Monday.

Then, next Monday it sets up triads.

This seems underwhelming for an on-boarding experience, since you just sit and wait till Monday AM to get triads setup. 

What else can you do?

**Comment by orta** [comment]
Buttons for "Tell me more about sup" and a "TLDR" - don't assume that people using it even know what it is.

I did mine today and the other person had never heard of sup, and just agreed to come along due to force of personality.

**Comment by dblock** [comment]
I removed an intro DM in https://github.com/dblock/slack-sup/commit/7625428b0807c079fd50d4c26a4cca17c68fd727 because I think it violates Slack TOS, but I think there's a better version where the first time a S'Up is created there's an intro message depending on whether you were introduced or not.

eg. 

* "This is S'Up, I setup triads." when everyone is new
* "Welcome Orta to S'Up, nice to see you again DB and Elisa. I setup triads."

**Comment by orta** [comment]
Yeah ^ is 👍 -  I think it could be a part of this message:

<img width="929" alt="screen shot 2017-08-23 at 22 59 06" src="https://user-images.githubusercontent.com/49038/29647345-b63f7dce-8856-11e7-8333-2e534506c589.png">

It's not a DM to everyone when it's installed kinda thing, it's a part of the actual usage flow
