### ISSUE TITLE
Pair remaining users

### ISSUE THREAD

**Issue by dblock** [dblock/slack-sup#27]
If the number of users doesn't divide by 3 someone will be left out. Web sup used to pair these together. 

Another option is to add them to existing sup's, therefore creating sups of 4.

**Comment by olafz** [comment]
A first step could also be to at least letting the one(s) left out know that they are left out. That way, there is a consistent interaction with S'Up every week

**Comment by dblock** [comment]
Good idea @olafz.

**Comment by dblock** [comment]
https://github.com/dblock/slack-sup/issues/41

**Comment by dblock** [comment]
Added `set odd`, which defaults to `true` in https://github.com/dblock/slack-sup/commit/9817b27cf20467100884e98401b09de79ffbac8a. This solves the case when there are fewer users than size.

**Comment by dblock** [comment]
In https://github.com/dblock/slack-sup/commit/dfb9629bace5a72061af8732661f9fdd79f5cba2 adding 1 odd user to an existing sup.
