### ISSUE TITLE
Give users an option to not meet certain people, such as in their team

### ISSUE THREAD

**Issue by dblock** [dblock/slack-sup#5]
cc: @orta, this is where we'd want team information in a custom field in slack

**Comment by orta** [comment]
You should be able to specify on your side, a profile attribute where you don't meet someone with the same value

**Comment by dblock** [comment]
This was implemented in https://github.com/dblock/slack-sup/commit/bf119b75db14b507855beefbbfa491cb26d981c8, @orta all we need to is to sync the data into Slack.
