### ISSUE TITLE
Add a "not yet" response for meeting.

### ISSUE THREAD

**Issue by dblock** [dblock/slack-sup#88]
Seems to me like the new 'sup app "checks in" too early to be useful. The options are "we already met" and "we could not meet" but there's no option for "we've scheduled a meeting but have not yet met". I don't want to lie to it

![image](https://user-images.githubusercontent.com/542335/101839606-aba27b80-3b10-11eb-880a-70b9d4e2e22d.png)

**Comment by dblock** [comment]
https://github.com/dblock/slack-sup/commit/00e421c6935f8f8fe7c1ecafe97327aff8c5e651

**Comment by jimm** [comment]
Thank you!
